In [2]:
import pandas as pd
import numpy as np 
import matplotlib as mp
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("C:/Users/2068671/OneDrive - Cognizant/Desktop/Datasets/hiring.csv")

In [4]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [5]:
df["experience"].fillna("Zero", inplace= True)

In [6]:
from word2number import w2n

In [7]:
df["experience"] = df["experience"].apply(lambda x: w2n.word_to_num(x))

In [8]:
df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000

In [9]:
df.isnull().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [10]:
df["test_score(out of 10)"].fillna(df["test_score(out of 10)"].mean(), inplace= True)

In [11]:
df.isnull().sum()

experience                    0
test_score(out of 10)         0
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [12]:
X = df.iloc[:, :-1]
X

experience  test_score(out of 10)  interview_score(out of 10)
0           0               8.000000                           9
1           0               8.000000                           6
2           5               6.000000                           7
3           2              10.000000                          10
4           7               9.000000                           6
5           3               7.000000                          10
6          10               7.857143                           7
7          11               7.000000                           8

In [13]:
y = df.iloc[:, -1]
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
lin = LinearRegression()

In [16]:
lin.fit(X,y)

LinearRegression()

In [17]:
lin.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [18]:
lin.intercept_

17237.3303137272

GRADIENT DESCENT

In [95]:
class gradient_descent:

    def __init__(self):
        self.coefficient_ = None
        self.intercept_ = None


    def fit (self, X_Train, y_Train, epoch, LR):
        m1 = 3000
        m2 = 2000
        m3 = 2000
        c = 17000
        for i in range (epoch):
            y_Pred = m1*X_Train.iloc[:, 0] + m2*X_Train.iloc[:, 1] + m3*X_Train.iloc[:, 2] + c
            m1 -= -2*LR*np.mean(X_Train.iloc[:, 0]*(y_Train - y_Pred))
            m2 -= -2*LR*np.mean(X_Train.iloc[:, 1]*(y_Train - y_Pred))
            m3 -= -2*LR*np.mean(X_Train.iloc[:, 2]*(y_Train - y_Pred))
            c -= -2*LR*np.mean(y_Train - y_Pred)
        self.coefficient_ = np.array([m1, m2, m3])
        self.intercept_ = c

    def coefficient(self):
        return self.coefficient_

    def intercept(self):
        return self.intercept_

    def predict (self, X_test):
        return np.dot(X_test, self.coefficient_.T) + self.intercept_

    

In [96]:
bgd = gradient_descent()

In [100]:
bgd.fit(X, y, 5000, 0.006)

In [101]:
print(bgd.coefficient())

[2829.19371417 1921.39840322 2201.89245905]


In [102]:
bgd.intercept()

17123.343577513235

In [286]:
bgd.predict(X)

array([52309.2102427 , 45686.59836973, 58186.83502418, 64040.93758137,
       67434.59860312, 61078.58931621, 75928.10470203, 79311.38834697])

In [287]:
y.values

array([50000, 45000, 60000, 65000, 70000, 62000, 72000, 80000],
      dtype=int64)